# Tags for everyone else:
- id: doi:10.1371/journal.pgen.1010470
  tags:
    - human diversity
    - denisovan introgression
  
- id: doi:10.1016/j.ajhg.2021.11.017
  tags:
    - indonesia
    - human diversity
    
- id: doi:10.46471/gigabyte.118 
  tags: 
    - marsupials

- id: 10.1186/s13059-023-02856-6
    - mpra
    - human evolution

# Duplicates to exclude:
- id: doi:10.1101/2023.11.16.567318
  remove: true

- id: doi:10.1101/2021.06.27.450107
  remove: true

- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review