- id: doi:10.46471/gigabyte.118 
  title: *De novo* transcriptome assembly and genome annotation of the fat-tailed dunnart (*Sminthopsis crassicaudata*)
  tags: 
    - marsupials
    - resource

- id: doi:10.1016/j.ajhg.2023.10.012
  tags:
    - human diversity

- id: doi:10.1126/science.adh0745
  tags:
    - perspective

- id: doi:10.1186/s13059-023-02856-6
  tags:
    - review

- id: doi:10.1111/febs.15885
  tags:
    - review

- id: doi:10.1038/s41576-022-00469-6
  tags:
    - perspective

- id: doi:10.1093/molbev/msab238
  tags:
    - papua new guinea
    - human evolution

- id: doi:10.1371/journal.pgen.1008749
  tags:
    - indonesia
    - human diversity
    - gene regulation

- id: doi:10.1093/molbev/msz037
  tags:
    - human evolution

- id: doi:10.1101/013888
  tags: 
    - iPSCs
    - gene regulation

- id: doi:10.1038/nature18964
  tags:
    - human diversity

- id: doi:10.1126/science.aab3761
  tags:
    - human diversity

- id: doi:10.7554/eLife.07103
  tags:
    - chimpanzee
    - iPSCs
    - resource

- id: doi:10.1371/journal.pone.0118307
  tags:
    - iPSCs

- id: doi:10.1038/nature13673
  tags:
    - human evolution
  
- id: doi:10.1371/journal.pone.0098076
  tags:
    - human evolution

- id: doi:10.1186/1741-7007-12-42
  tags:
    - gene expression
    - methods

- id: doi:10.1371/journal.pgen.1003912
  tags:
    - human diversity

- id: doi:10.1186/1471-2156-14-87
  tags:
    - methods

- id: doi:10.1111/ahg.12028
  tags:
    - human diversity
    - india

- id: doi:10.3378/027.085.0313
  title: Evolution of the Pygmy Phenotype: Evidence of Positive Selection from Genome-wide
    Scans in African, Asian, and Melanesian Pygmies
  tags:
    - human evolution
    - human diversity

- id: doi:10.1038/nrg3229
  tags:
    - review
    - gene regulation

- id: doi:10.1016/j.ajhg.2012.05.015
  tags:
    - human diversity

- id: doi:10.1007/s00439-011-1111-9
  tags:
    - methods

- id: doi:10.1126/science.1215040
  tags:
    - human diversity

- id: doi:10.1016/j.ajhg.2011.11.010
  tags: 
    - human evolution
    - india
    - human diversity

- id: doi:10.1093/molbev/msr190
  tags:
    - human evolution
    - india
    - lactase persistence

- id: doi:10.1126/science.1211177
  tags:
    - human diversity
    - human evolution

- id: doi:10.1093/molbev/msq288
  tags:
    - human diversity
    - india

- id: doi:10.1038/ejhg.2009.168
  tags:
    - human diversity
    - india

- id: doi:10.1038/hdy.2008.89
  tags: 
    - human diversity
    - human evolution
   
- id: doi:10.1007/s00439-007-0432-1
  tags:
    - cftr
    - hutterites

- id: doi:10.1101/gr.224436.117
  tags: 
    - gene regulation
    - iPSCs

- id: doi:10.1371/journal.pgen.1010470
  tags: 
    - denisovan introgression
    - human diversity

- id: doi:10.1016/j.ajhg.2021.11.017
  tags:
    - indonesia
    - human diversity
    - gene regulation

- id: doi:10.1186/s13059-023-02856-6
  tags:
    - mpra 
    - human evolution

- id: doi:10.1371/journal.pcbi.1007128
  title: Open collaborative writing with Manubot
  authors:
  - Daniel S. Himmelstein
  - Vincent Rubinetti
  - David R. Slochower
  - Dongbo Hu
  - Venkat S. Malladi
  - Casey S. Greene
  - Anthony Gitter
  publisher: PLOS Computational Biology
  date: '2020-12-04'
  link: https://doi.org/c7np
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed
    do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
  - type: manubot
    link: https://greenelab.github.io/meta-review/
  - type: source
    text: Manuscript Source
    link: https://github.com/greenelab/meta-review
  - type: website
    link: http://manubot.org/
  tags:
  - open science
  - collaboration
  repo: greenelab/meta-review
  plugin: sources.py
  file: sources.yaml




# remove duplicates:

- id: doi:10.1101/2023.11.16.567318
  remove: true

- id: doi:10.1101/2021.06.27.450107
  remove: true

- id: doi:10.1101/2020.07.09.196444
  remove: true

- id: doi:10.1101/2020.09.25.313726
  remove: true  

- id: doi:10.1101/002261
  remove: true

- id: doi:10.1101/008862
  remove: true



# Classify preprints:

- id: doi:10.1101/2024.04.11.24305690 
  type: preprint
  publisher: medRxiv
  tags:
    - human diversity
    - AVE

-id: doi:10.1101/2024.05.07.593052
  publisher: bioRxiv
  tags:
    - indonesia
    - human diversity

- id: doi:10.1101/2023.02.13.528361
  title: *Cis* -regulatory landscapes of the fat-tailed dunnart and mouse provide
    insights into the drivers of craniofacial heterochrony
  publisher: bioRxiv
  tags:
    - marsupials

- id: doi:10.1101/2022.04.24.489025 
  publisher: bioRxiv
  date: 2024-05-06
  tags:
    - indonesia
    - microbiome

- id: doi:10.1101/2021.01.07.425684
  title: Transcriptomic profiles of *Plasmodium falciparum* and *Plasmodium vivax* -infected individuals in Indonesia
  publisher: bioRxiv
  tags:
    - indonesia

- id: doi:10.1101/466631
  publisher: bioRxiv
  tags:
    - chimpanzees
    - iPSCs


# tester

- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review